
categories = ['kickboxing', 'yoga', 'powerlifting', 'crossfit', 'rock climbing', 'bodybuilding', 'parkour', 'boxing', 'MMA']

gym_data = [['kickboxing', 'Bay Area Boxing', '4', '5', '210 El Camino Real, Belmont'],
            ['kickboxing', '3rd Street Boxing','5', '5', '2576 3rd St, San Francisco'],
            ['kickboxing', "King's Boxing Gym", '3', '4', '843 35th Ave, Oakland'],
            ['yoga', 'Left Coast Power Yoga', '3', '5', '3702 Grand Ave, Oakland'],
            ['yoga', 'Hot Spa Yoga Oakland', '3', '4', '2008 Park Blvd, Oakland'],
            ['yoga', "Love Story Yoga", '4', '3', '473 Valencia St, San Francisco'],
            ['powerlifting', 'Speed Power Strength', '4', '5', '2140 Livingston St, Oakland'],
            ['powerlifting', 'Bay Strength', '5', '4', '1440 University Ave, Berkeley'],
            ['powerlifting', "Max's Gym", '3', '5', '1313 67th St, Emeryville'],
            ['crossfit', 'United Barbell - CrossFit SOMA', '5', '5', '681 4th St, San Francisco'],
            ['crossfit', 'Grassroots CrossFit', '4', '5', '2036 Blake St, Berkeley'],
            ['crossfit', 'City CrossFit', '5', '5', '2 Brooks St, San Francisco'],
            ['rock climbing', 'Bridges Rock Gym', '4', '5', '5635 San Diego St, El Cerrito'],
            ['rock climbing', 'Great Western Power Company', '4', '5', '520 Thomas L Berkeley Way, Oakland'],
            ['rock climbing', 'Mission Cliffs Climbing', '5', '4', '2295 Harrison St, San Francisco'],
            ['powerlifting', '24 Hour Fitness', '3', '3', '3950 Alameda Ave, Oakland'],
            ['powerlifting', 'Orange Theory Fitness', '3', '4', '2610 5th St, Alameda'],
            ['powerlifting', 'Fitness SF - SOMA', '4', '4', '1001 Brannan St, San Francisco'],
            ['parkour', "Traverse Fitness", '3', '5', '1 W Barret Ave, Richmond'],
            ['parkour', 'Athletic Playground', '4', '5', '4770 San Pablo Ave, Emeryville'],
            ['parkour', 'NXGA Parkour', '3', '4', '44360 Technology Dr, Fremont'],
            ['boxing', 'Lightnings Boxing Club', '3', '4', '5845 Macarthur Blvd, Oakland'],
            ['boxing', 'Boxing for Health', '3', '4', '452 Santa CLara Ave, Oakland'],
            ['boxing', 'Bay Area Boxing', '4', '5', '210 El Camino Real, Belmont'],
            ['MMA', 'Bay Area Fight Academy', '4', '5', '1625 Industrial Pkwy W, Hayward'],
            ['MMA', 'CATCH MMA', '3', '5', '1922 Webster St, Oakland'],
            ['MMA', 'Dragon House', '4', '4', '4696 Mission St, San Francisco']]